# 生成网址所用域名
baseURL = "https://bonfire8458.github.io/"
#baseURL = "http://192.168.1.61:1313/"
# 语言编码(中文: zh-CN)
languageCode = "zh-cn"
# 默认的内容语言
defaultContentLanguage = "zh-cn"
# 创建robots.txt，建议设置为true
enableRobotsTXT = false
# 启用 Emoji; see emoji-cheat-sheet.com
enableEmoji = true
# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true。Hugo会自动提取文章的前70个字符作为摘要，hasCJKLanguage = true才能发挥更好的效果。
hasCJKLanguage = true
title = "姆Q的大圖書館"
# 主题
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  

[params]
  author = "Bonfire8458"
  avatar = "./images/favicon.png"
  favicon = "./images/favicon.png"
  #description = "* 秉持勇气与智慧，拿起心理学这根魔杖，舞动当下</p><p>* 咖啡续命中ing..."
  description = "咖啡续命中ing..."
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/Bonfire8458"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/Bonfire8458"
  [[params.social]]
    icon = "telegram"
    name = "Telegram"
    url = "https://t.me/bonfire8458"

[params.style]
  darkestColor = "#11001A"
  darkColor = "#321942"
  lightColor = "#afbac4"
  lightestColor = "#FFFF00"
  primaryColor = "#BC5DF8"

